### ISSUE TITLE
Add list of supported games? is yakuza like a dragon  supported?

### ISSUE THREAD

**Issue by jacksauciboie** [Fr33dan/GPSaveConverter#14]
like the title is saying i am downloading yakuza like a dragon on gamepass and i am wondering if i can get steam save file (75h playtime) to xbox gamepass ver also achievements if not i will try to get them again

**Comment by jacksauciboie** [comment]
there's yakuza like  a dragon save editor but for UWP version it only decrypts and doesnt encrypt https://github.com/SutandoTsukai181/yk2_save/releases

**Comment by jacksauciboie** [comment]
Another reason why i posted this i wanted to try software with steam save files of psychonauts 2 and trying to get them to gamepass ver but i get error about path of xbox ID

**Comment by Fr33dan** [comment]
There is a [list](https://github.com/Fr33dan/GPSaveConverter/wiki/Game-Compatibility) available on the wiki. Unforunately it's rather small because each game needs [file translation(s)](https://github.com/Fr33dan/GPSaveConverter/wiki/File-Translations) created for it individually.

I documented these in the Wiki in the hopes that users could create them themselves (and hopefully share them here for others to use) but so it's been beyond the comfort level of users and I've had to create them myself working with the user. This usually involves a bit of trail and error which has made the process slowgoing.

For any game you need a file translation for I need to know the file structure of the non-Xbox save files, and then the names of the containers for the Xbox save files (which are shown in the converter).

The tool you linked to seem to be more about converting the files to a format wherein you can edit them manually. They don't seem to be aware of the overall structure UWP/Xbox uses to track save files which is likely why they can only decrypt from there and not encrypt. If the UWP file is edited, but the assosciated structure is not the file will be reverted. They also don't seem to address that the UWP save file (unless it's different than every other game) will not be named "data.sav" but a string of 32 characters with no human meaning.

**Comment by Fr33dan** [comment]
There's a few different things being asked here, but for the sake of project organization I'm treating this one as just about the list and closing it as there is one on the Wiki. I will address further issues with Yakuza in the thread dedicated to just that.
