### ISSUE TITLE
Issue whit forza horizon 5

### ISSUE THREAD

**Issue by Miguel118abreu** [Fr33dan/GPSaveConverter#20]
![2022-10-22](https://user-images.githubusercontent.com/116463497/197361883-120c9490-d221-47e5-bb09-e133d97ea6d8.png)

**Comment by Miguel118abreu** [comment]
It s in portuguese

**Comment by Fr33dan** [comment]
I've seen the message enough times to understand it in most Latin derivative languages. It's just saying that there is no data where it is expecting to find game files. It's not finding your Xbox save files for some reason. Go-to File > Preferences and change the Log Level to TRACE. Then restart the converter and try again. It will not work but the file .log file will be updated with more information. Then open that file and paste it's contents here.

**Comment by Miguel118abreu** [comment]
where is the file that you want me to copy over here?

**Comment by Miguel118abreu** [comment]
I already change to TRACE

**Comment by Fr33dan** [comment]
It should have been created next to the save converter exe. I would guess this is in your downloads folder.

**Comment by Miguel118abreu** [comment]
[GPSaveConverter.log](https://github.com/Fr33dan/GPSaveConverter/files/9847133/GPSaveConverter.log)

**Comment by Miguel118abreu** [comment]
it was to long to put in here so there is the file

**Comment by Miguel118abreu** [comment]
My xbox username is "Miguel118"

**Comment by Miguel118abreu** [comment]
and after the name has #1696

**Comment by Miguel118abreu** [comment]
and my steam user name is miguel_abreu0

**Comment by Fr33dan** [comment]
Sorry for the confusion, I mean your Windows username. Although I'm guessing not since none of your other usernames use special characters. Lets check the rest of the filepath, in english the file path for FH5 Xbox save files is C:\Users\[YourUsername]\AppData\Local\Packages\Microsoft.624F8B84B80_8wekyb3d8bbwe\SystemAppData\wgs . What is the matching path in your language?

**Comment by Miguel118abreu** [comment]
My windows username is Miguel

**Comment by Miguel118abreu** [comment]
when i go to users only shows public and user
![2022-10-25 (2)](https://user-images.githubusercontent.com/116463497/197738701-c62e53ab-89a8-4aca-84fa-8f81f537b410.png)

**Comment by Miguel118abreu** [comment]
and inside of user i cant find app data only save games but in side there is nothing
![2022-10-25 (3)](https://user-images.githubusercontent.com/116463497/197739141-d47b00c3-089b-43f6-93dd-d792ad61e77c.png)
![2022-10-25 (4)](https://user-images.githubusercontent.com/116463497/197739299-031210f9-f640-4928-96e6-73dbd8c86bba.png)

**Comment by Miguel118abreu** [comment]
save games translate to jogos guardados

**Comment by Miguel118abreu** [comment]
Is there something i could do to help?

**Comment by Miguel118abreu** [comment]
The save files where hidden and they are where they were suppoused to be. What do I do now?

**Comment by Fr33dan** [comment]
I've just been looking at the relevent code, and it turns out that since the game displays in the list it must mean the WGS folder was detected which means I've been chasing the wrong rabbit hole with this file path investigation.

Since you found the files manually would you mind posting a screenshot of the wgs folder? It must be something about it's contents that are not being parsed which is why you are not seeing any save files in the xbox side of the converter. But the file open does not have error handling so if the files couldn't be accessed at all the program would crash similar to the error shown, but with a different message than the object reference error such as "file not found". 

Depending on what your WGS folder looks like I may need to find a way to access your containers.index or container.x files (in sub-folders of wgs).

**Comment by Miguel118abreu** [comment]
![2022-11-02](https://user-images.githubusercontent.com/116463497/199492215-a911a339-e52e-4a33-863c-75b372abbbfa.png)
Here it is

**Comment by Fr33dan** [comment]
Ah! There are two many folders here. Make a copy of these files somewhere just in case. Then delete the ones with the modify date in January (I am assuming the one with the date in October is the one that should be used).

**Comment by Miguel118abreu** [comment]
There are no january files there are two from november( the last time i played ) and one from october (in portugal is day/mouth/year)
By the way the november one is larger then the october
I assume you should have only two right?

**Comment by Miguel118abreu** [comment]
i just started the game to se if the date on the files would change and it did so i assume the last two are the right ones

**Comment by Fr33dan** [comment]
Oh my bad, I remembered the European date format when reading the first folder, but then my brain fell back to the US way when looking at the second two. 

This folder should contain a `t` folder and one longer folder per xbox account (Notice the first part of that file name matches your xbox profile ID shown in the converter). If you had two xbox profiles on this PC then you would have multiple long named folders here, but with different names before the underscore. Since you have two with the same xbox profile ID and I didn't account for this scenerio I'm not sure which one it picks. Whichever one it is picking must be corrupt (which is likely why the new one was created by the game).

I think you should delete the older one and try again.

**Comment by Miguel118abreu** [comment]
now the save files appear but a error is still there(i m not sure if a new one) (i can skip the error)

**Comment by Miguel118abreu** [comment]
![2022-11-02 (1)](https://user-images.githubusercontent.com/116463497/199560750-4569181d-74bb-42d8-999f-6f12ce390c1d.png)

**Comment by Miguel118abreu** [comment]
![2022-11-02 (1)](https://user-images.githubusercontent.com/116463497/199560829-ea89b096-d720-4470-a007-7433f9e1226d.png)

**Comment by Miguel118abreu** [comment]
![2022-11-02 (2)](https://user-images.githubusercontent.com/116463497/199560885-ee38e666-7ccd-4987-9efb-6ed289152ca9.png)

**Comment by Fr33dan** [comment]
Unfortunately you can only transfer the profile data and not any liveries or garages. You must select just the profile data file from the Xbox files and use the single arrow to transfer just that file. The double arrow attempts to transfer all files, which will not work since those files are not supported.

It is my understanding that the liveries and garages will then be restored in the background by the game itself, but no one has ever come back to explicitly state this is the case, only implied it.

**Comment by Miguel118abreu** [comment]
Two questions ?
Do i need to press anything in the bottom side before i press the arrow?
Can i play in my account in ms after i transfer the data? (to see the codes of the tunes and the liveries)

**Comment by Fr33dan** [comment]
No, the profile data on the bottom should be selected when you select the file on the top.

I don't think it would be a problem.

**Comment by Miguel118abreu** [comment]
just to be sure i don t want to ruin all
![2022-11-02 (3)](https://user-images.githubusercontent.com/116463497/199564695-4f71449d-df74-4783-9ef7-ac657816ca50.png)

**Comment by Fr33dan** [comment]
You want the one that says "ProfileData" that is 3 up from the one you have selected now.

If you are worried you always can make a copy of both folders and copy them back if there is any issue,

**Comment by Miguel118abreu** [comment]
It worked thank you so much
Before i start playing do you know why did i have one file that should not exist

**Comment by Fr33dan** [comment]
I'm afraid I don't know why it happened, but I will add code to better account for this scenerio next time I get a chance to work on this properly.

**Comment by Miguel118abreu** [comment]
ok
