### ISSUE TITLE
Game Compatibility - Generation Zero

### ISSUE THREAD

**Issue by Izooc** [Fr33dan/GPSaveConverter#22]
Hi!
When i try to convert the Xbox Save files to non xbox save files i get:
"Relative file path translation to Xbox file ID not found"
Ive read from other issues that it means that the game is not supported!
Was wondering if there is anyway for you to add the game support
Thanks

**Comment by Fr33dan** [comment]
Oh my, I'm so sorry I missed this.

In order to create a file translation I need to know the file formats of both save files. If you have the game from a non-Xbox storefront run it enough to create a save file. Run the converter and select the game. Then you can used File > Copy Save File Table(s) which will put the a copy of the file tables on the clipboard. You can then used Ctrl+V to paste the tables here so someone could use that to create the file translations required for compatability.

**Comment by Izooc** [comment]
Hahaha that's fine, I'll try that later today when I've got the game redownloaded (I stopped playing it but should be helpful for somebody else lol)

**Comment by Izooc** [comment]
How have i forgotten this! Absolutely awful although i didnt have the game on steam anyways at that time and only gamepass. Ill get it downloaded on steam and get this sorted once and for all :).

**Comment by Izooc** [comment]
Turns out i dont have it on another storefront...
