### ISSUE TITLE
Epic Games Support

### ISSUE THREAD

**Issue by VictorKruger** [Fr33dan/GPSaveConverter#42]
Hello,

I would like to request the ability to use the save converter to be able to import/export xbox/pc game pass save files to/from Epic games.

Thank you,

**Comment by Fr33dan** [comment]
The short answer is that it already does.

The long answer is that the tool is very carefully designed and worded to say "Xbox" and "non-Xbox" explicitly because it is intended to work with multiple game storefronts. If the game you're working with keeps it's save files in say "My Documents\Saved Games", the converter will work regardless of where you bought the game (assuming the game is supported).

The tricky bit is that some games save file location incorperate the Steam user ID in the save file folder. I don't know what these games do with their save files when they are installed from another storefront such as EGS. I think it would be good to have support for such scenerioes, but so far no one has provided one. Since I don't know what happens in this situation and I'm not psychic I can't write code to handle it.

Until someone has a game on the EGS with this issue and reports it to me with enough detail so I can understand what happens in this case I can't do anything.

**Comment by VictorKruger** [comment]
okay thank you, I'm trying to transfer a save from Hitman 3 (world of assassinations) to epic game store version.  I'll collect as much info as I can and create a new ticket.
