### ISSUE TITLE
NullReference Exception when WGS folder exists, but game not in UWP library.

### ISSUE THREAD

**Issue by At-M** [Fr33dan/GPSaveConverter#8]
Hi,

the program throws a nullpointer/reference when starting and shows a broken thumbnail below Forza Horizon 5

![nullpointer](https://user-images.githubusercontent.com/2135630/178161853-96017ffd-0d66-438e-869b-69fd793c468a.png)

I downloaded the latest release of GPSC, and have no steam folder for forza setup yet, so maybe thats an issue

**Comment by Fr33dan** [comment]
You will need to run the game from Steam to create the folder so that will be an issue, but that is not the cause of the error shown.

The script that fetchs the UWP package information returns the location of the thumbnail from the Xbox installation. That thumbnail is what is used for the game selection table. Most likely something is going wrong with the parsing of this scripts results resulting in the thumbnail data not being populated. Please use the preferences to change the log level to "Trace" which will then make the GPSC dump the scripts results into the log file, I can use this to debug the problem.

**Comment by At-M** [comment]
It seems that an old install of Forza Horizon 4 (I can't remember if it was gamepass, demo, crosssave from xbox or just the basic standard edition) bugs out the program.

I've found two "folders" (look like folders but are some kind of file links) in C:\Program Files\WindowsApps, called:

1. Microsoft.SunriseBaseGame_1.473.411.2_x64__8wekyb3d8bbwe
2. Microsoft.SunriseBaseGame_2021.630.1925.2_neutral_~_8wekyb3d8bbwe

after some quick googling, they both refer to FH4, deleting or opening them won't help.

There are a few entries in the registry with "Microsoft.SunriseBaseGame", one of them shows the following:
![fh4sunrise](https://user-images.githubusercontent.com/2135630/178596852-c205d048-ab56-48ab-85cd-78ac871792fa.PNG)
)
so it definitely has something to do with FH4

I haven't tried deleting the regkeys for the "sunrisebasegame" yet though


[GPSaveConverter1.log](https://github.com/Fr33dan/GPSaveConverter/files/9096849/GPSaveConverter1.log)

**Comment by At-M** [comment]
It seems that simply de-registering the application package with powershell works, now it doesn't throw the error anymore:
I guess it deinstalled the game back then, but didnt remove the appxpackage...


Get-AppXPackage Microsoft.SunriseBaseGame | Remove-AppXPackage

the missing icon is gone and no errors are popping up. I'm not sure if you consider this closed, so i'm gonna keep it open for you to judge
